---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/infisical-infra
  - namespaces/infisical-node-kenaz
  - namespaces/infisical-backup
  - namespaces/actual
  - namespaces/auth
  - namespaces/cert-manager
  - namespaces/monitoring
  - namespaces/glance
  - namespaces/gatus
  - namespaces/csi-rclone
  - namespaces/k8up
  - namespaces/ingress-internal
  - namespaces/ingress-edge
