---
node:
  hostname: kenaz
  os: fedora
  workflow: k0s
  k0s_role: controller+worker
  mesh: true
  ip: "{{ lookup('protonpass', 'pass://futharkd/kenaz/ip address') }}"
  initial_user: fedora
  initial_port: 22
