node_ip: ENC[AES256_GCM,data:XtaiTcV39LLQnwJo/A==,iv:cy3Yvd+9aZZa2l58eHvfgfRqPvHkgefoow4kJ4idg9E=,tag:IZWsdGS8++XKRRGTjc8roA==,type:str]
node_mesh_ip: ENC[AES256_GCM,data:V7GQ4wWHZKlVVYII,iv:v6DZc/rm/tiApZ/vNzI2hogHbMIgpQ8ujOnRp6dcxQo=,tag:NKA5HKWxJKxjy+GXIaeHNQ==,type:str]
sops:
    lastmodified: "2026-07-27T16:29:00Z"
    mac: ENC[AES256_GCM,data:8dWkPNSPq0NtkJZYSdYqv09b8ExhhiZ1mfQD2p0cTywUJaCiYMMin1BmdcoAw43e5N9oeDL9H2ca3RoEJclLrVYmWqMgoorP5j7VAaYjaRbQC8x1Zh1Sa53oYWVYnBqIIR6Zw8lghNcEri8u1WtpxLmuDpd+FHDR0t1Z3mykJYw=,iv:uMOYJw/P/tYacaY2P/F+m+k2+uXr8X6dLooDnP7GrCo=,tag:ftetVVdy0O2KLdiUYWKwvQ==,type:str]
    pgp:
        - created_at: "2026-07-27T13:56:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4HEqjsrLGq9AQ/+Li5gsgPpPGZ74rnvnct/pRvz2cItEFszR+7dNNYhxRqB
            rvFzcI2bKdlB0jP35jRB9pIrIpfDIquW2JYhI/IYLwixYVT87h0MU6yzmvNquoUK
            2ug95YyghsTcyzKU/VZIRHjvSL2/9xZW/lK71F1EUvjijR8RHwfo0hAy3DWI+QWf
            MxB6BD7gcih4ToFBuxkT+jU8Hr9cEBQJiVlsZ2F62Y9/DYoWJ/IvCD7G9QQipFRk
            LJS3Xv8QDIvaKGFq7UReg+LuJuEXL0aUCFbHuoumm/PVee8oK5zqEFd+kJugEwL8
            SxGj5U+NVqJhvgZdR9ypyoYyt9rJhrJ55NKFxAUgfvF8QK6zqLN2EOdxXU2h5ZgO
            JspPs1SzyeGGqerKjtO5LtN4eiKddEhgfqmWicjBMjfS0EoOa6JRJwlt/yiUImz0
            Ynvdb/YhsHGc0sUyXkVZcctsQbW76nZzdClBVzayaFpKQJBIdl9WeKYLkZbE15Op
            d9DYrFSbrv2+cRNGyQaVHCpFRHBWxaHZ6gG76BRi9SM679kQwVImfWgVPGTXHuA4
            GfXo2U/marDjRxJyxtZnBZXyXbxl4hwE7xoEJ/yB/rvJd9lFxDqS5dVElRJ5E9Hl
            YGunMElPN2MFXHKUu0hJpcA/8gkQJHU7HcLknSMrD98iChTolZeDljoJuFdPQF7S
            XgEpZtSQwW9dDsErWukcKJKHz8dbyr70Hq1rgfzWKGR9UZtB0hP8EsrNKTPotpx5
            Jv6DK63h8qjIAyAUYpTyhO6FhmcYRD3NtymO1BGvZSjy+qCaEjgvD3661a7a+qk=
            =/TkL
            -----END PGP MESSAGE-----
          fp: 100E6328B87F82112F2A932F7B5D8E73CC72848C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
