---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  ans: .taskfiles/ansible/Taskfile.yaml
  bao: .taskfiles/bao/Taskfile.yaml
  ops: .taskfiles/operator/Taskfile.yaml
  tf: .taskfiles/tofu/Taskfile.yaml
  pm: .taskfiles/podman/Taskfile.yaml
  k0s: .taskfiles/k0s/Taskfile.yaml
  fx: .taskfiles/flux/Taskfile.yaml

tasks:
  default:
    silent: true
    cmd: task --list
