---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  ans: .taskfiles/ansible/Taskfile.yaml
  ops: .taskfiles/operator/Taskfile.yaml
  tofu: .taskfiles/tofu/Taskfile.yaml

tasks:
  default:
    silent: true
    cmd: task --list
