---
# POCKETID_ENCRYPTION_KEY: openssl rand -base64 32, stored once in Infisical at /infra/auth.
# MAXMIND_LICENSE_KEY: from the MaxMind account, same folder. Both land in one Secret because
# a single secretPath maps to a single target. app/deployment.yaml mounts each as a file, and
# maps the key to the filename Pocket ID expects.
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: pocketid
  namespace: auth
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-infra
  sources:
    - projectSlug: futhark
      environmentSlug: prod
      secretPath: /infra/auth
  targets:
    - kind: Secret
      name: pocketid-secrets
      namespace: auth
      creationPolicy: Owner
  syncOptions:
    refreshInterval: 1m
