---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-storagebox.yaml
  - pv-gdrive.yaml
  - pvc-storagebox.yaml
  - pvc-gdrive.yaml
  - pvc-hist.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
