---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/actual
  - namespaces/auth
  - namespaces/cert-manager
  - namespaces/monitoring
  - namespaces/csi-rclone
  - namespaces/ingress-internal
  - namespaces/ingress-edge
  - namespaces/tailscale
