#ENC[AES256_GCM,data:eexb9nEkqsUqrTqEiBnPSLwAJzbXXgWChB2mA2GEpDFFHTIL+uQLQrqu,iv:N52hDlkMJounN1+H0co6cmr59xehcj7JZHWeKq8j5Fo=,tag:RuV0s48v71earzVFw3Op9w==,type:comment]
apiVersion: ENC[AES256_GCM,data:RdU=,iv:KZrxcIrreulADNNG/5VxoWsopqN2tn/wUl4vdIOaii0=,tag:D1YZvp3pfP6CoFxMBZOKZg==,type:str]
kind: ENC[AES256_GCM,data:zQRvmOmW,iv:4HEIubbrRmJX86H/N9G09E0o6T4vMw2oXQpBLJ4FMY4=,tag:dJKJwlK6ZO/w/bvwyHRTDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+IKxgt1gcZyqzquCOMQ=,iv:EtmXPy+Moc9CYr/FWvHv4m7khJpec9Jcpe1rZc7QUk4=,tag:+nBGBICbsWQMJt+aeuqE9g==,type:str]
    namespace: ENC[AES256_GCM,data:4/jy0kUSInmh/CI=,iv:FW6oddZ4XdboOQc/t9Z0UR3yCtH18CVlNA2uEHSQ2lk=,tag:ohOtVbqU99tSGRz3+wIfwg==,type:str]
type: ENC[AES256_GCM,data:j4q62tzm,iv:9LgMmzjopnv1XXgPm2T0P2R12Ad24KFZ0TLBAt8GThg=,tag:yRVWWkEfD5APKmD3KZA7Ag==,type:str]
stringData:
    DOMAIN: ENC[AES256_GCM,data:UJgEjD8Lgw==,iv:tgsLZ0/jND+50T9nKPUlaxtxmywzVwSuckG9bfo10y4=,tag:4xgpEpCRt20oocMNYs5BVg==,type:str]
    SUB_INTERNAL: ENC[AES256_GCM,data:pO4=,iv:QlIBGkfm9Rc5FZQvwKHg5w8/YpYpYuUZjGGTmryidA0=,tag:kFsAJ3clbGerDXnWyzdHoQ==,type:str]
    SUB_NODES: ENC[AES256_GCM,data:og==,iv:vWXt56aHLSyMDnZyws+0wlJPcSbf8ySNOyLcxgqnNcA=,tag:DTDAKtt0JDa+crDjS6WdlA==,type:str]
    PUBLIC_IP: ENC[AES256_GCM,data:ua9DHZQCJLZ1u9+A,iv:DxGXMgb/6NhWaJPO5AqJ4BN/1nxGjY04IGT4ps3ycV0=,tag:IoPnwd8VhExe54G3B8URcg==,type:str]
    MESH_IP: ENC[AES256_GCM,data:jcXlcgcoVD2ClsrU,iv:PakAOv3XH8OVFYLedkuIXmpUQKKchOlnGiUX4m68Bb8=,tag:/l1fZfNXejbBvgqqFLGvfg==,type:str]
    B2_BUCKET: ENC[AES256_GCM,data:sPlwgxz377B9XB5wMwo+WrTCuQ==,iv:sQ4vDT7ehcRlNJp/NSso1v8YWIxs959nBSiSiTM7Dso=,tag:z4umNfQo9qtorTUZACJfag==,type:str]
    B2_REGION: ENC[AES256_GCM,data:9PfJoOj1u/vGwDHqEks=,iv:+1cPQnZMDYAFI4vPM3y37ZOJT0ue+mmIv35B1Zh83K0=,tag:reA+vw6p3Aw+PLkZC2Q74A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSU01RVpnYUtRbVE0eFFu
            cHNPNHZmZS9LZGRzZzZ3SDk5NTlyRDF4QkNZCjFWc0NYMzNwai94cVB4KzJaaDZM
            VW92Umt5RXUyMU5YSk1QTmIwaDAvSjQKLS0tIHFBaU9OVGI4enE2UXFhUWI3c01U
            RWpaTWcvMDI4V2U5TElzOGtMZlowR1EKl6r9ZcNXvWpBotYBFs6yzlJE+0ckQRNf
            14HEEeMF+hiY11stUbUrXOks6wp1JPoX6GpTAenGm8+dT1NCBIRAMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nxkppuywt7zwzupqz3x5mcvrym7995wfgcuyc7fj9pp6fm03yss97483a
    lastmodified: "2026-08-10T21:05:36Z"
    mac: ENC[AES256_GCM,data:iVE5g3dLPuDdN8giPBF13jBEGXNlgEGuA6lRvCzWp2NouamjXiR38ZGr74jb3S290k7McCySplTQuxK3mHHxdaB/W/7Q7At0GpI22aziPYY2+C5gmmloa5WoWSj67k/UmM1ijXM1m1qdmJt4qNComZ/yVONtRtxUWdw69k1FXp0=,iv:BELXLXgHMR18kd9LRXzZzb2YpXwA+Y/Pmzbif8hE8lU=,tag:3feEVslCL79pVm3Mj7feaw==,type:str]
    pgp:
        - created_at: "2026-08-10T21:35:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4HEqjsrLGq9AQ/+K+Jd6G1uf6Orh7JOcZ7LsXvXLBrF6INDGboKEFSHIXFs
            E/orgc/gWlbJSwKSRY2GFsO4O1JNRrBbP2CnBaOz285F+5eXfy59hAJa21hBjj9c
            nzuJeqef2jK1wSXgAzPNUp0lHStqu+TTeIMQbDlIK88QKKFCs6H6tSRkbxHddhyj
            o3gbYZTHp/Ov8qWG4lKzaL/dm6F+I8m4I145DDRTMmdQkSl7ppXQE8jAFABO6kxE
            /FV2h3Uvt8SxRH5pfoghxEIiLjHSvfiB36OQswJqz7s+lYbUzJRymEcZaqPLzO13
            M3ENohrF5LGtRg5JhWo0o82wZJufDwlTkOZF22kXHbD7frFkSh75bjfHjPUqJHjB
            P5J2mYNMdW2CQWSW8hZ+fzJDwtnai3xNJuCIHG432uQTO9ss6Ec846O1IorLAAVj
            njjT0ElcuTaTyaDzAWlk2Zyw0R5Cm936Z+uAToiNPCOH2vJqIpTbHQo95ohUhamI
            rsgZXu+N6qHG/1/YUIyOmz5NRUqrJHQfc3pkji0j3c8gvJ3IL6h6dW5BhMA46F/F
            +cecaK7M7TU3JS0+WqCYiQGml26s9OorjEJndyq3FVpwj/31V5v5L0dc75ckBveC
            5yofpW+NLkCyf7I1Ydt+z7du1AaSN9PoZo6VrvPltD+WE+AKcm2bhCem2T+tpqDS
            UQE2IGtJyP13AMfrwdkZuADPr5EI8mL1JpjuwBywdL8cADynIvxxJgRoDsbQCMxa
            LfuZv9RIKyZTofPEUD/xuuVA+xPP1zBsFN+2kEDSeJM06Q==
            =2qU0
            -----END PGP MESSAGE-----
          fp: 100E6328B87F82112F2A932F7B5D8E73CC72848C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
