---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd/source-controller/main/config/crd/bases/source.toolkit.fluxcd.io_ocirepositories.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
  ref:
    tag: "2026.5.6"
