---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd/source-controller/main/config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical
  namespace: infisical-operator
spec:
  interval: 1h
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
