admin:
    user: ENC[AES256_GCM,data:bTknH7Vgog==,iv:x8JOuLZk9bX98XpLZGep+MwzWqca1r4JHes0CKfwfew=,tag:+BygQbCJZeMMgo2Ii3z6jg==,type:str]
    ssh_pubkey: ENC[AES256_GCM,data:C5wlhBBVCl6XrNOdaYJqFSUtrs1xmnp/wmQkl6gEb8bfofgLsVzXn+nZplQvwFBFkMF7cnMcj2wh5f+B8n3TA/QaNoTCdKRLJmlbGdH6xn+7SWAOJUtw9Hru6I8k7EIPT1DMUFkVYmMJPoeKyo3KbZNNPPTcTofrNZhCncC3yknwu0FqT/DZoidC4QK0D8gVvfBlZaesmCEL8apcmg70Cr52bMVuAPzLM7a1OFimgEtqMEej6xnvPQtk3pOTkrihegRVgiMUI2bUEpbJ6uRYux2Mw+uSDAJrs61fjFa50cppPr861IXBYChrHm/69jib+O3s7cW2UntkxXwlsGRAXbdRyMh28/fN03f+Jr7l4eP4ZGb3/UrXbaEux7u7g5cOuWu4AxbqxxSB0B+9Wwqrz2tbstZRDQj6fEsW2/6JcoeUAPMPadcOSMfDtvfqef/xvIT9PSfJBQ0kaBB3emWiDiqsT/xje+hByAUYPwaX4sy9OV3maddYjxnvy0SEv6tJ3Ki5DORtldeo4Y51D0wpbgazdw4wTDkxLx9lVprLMEDCV42A8sM5CYpZhZu3zRtCjSgtpttPK8Zcw1j3bQEC1WazTssH6Fxn4K9iAwwbO3YrZ6vmhn7DOg8WmR3fqzgBXQyh6DIysXh6F9/yHE2v8j3Vbzz5VmAoxq4/KNoHCrm5MXCewiau47AbWi81AxBSlvxPvfnwH2XUHf/P4Aj37mHtV3K9pV4pYGxvLwk0O0VW6d+2wUpPv69cETT2s6Gx+JdMHQNLce2cRlTgZCY2Kqun7aJyHLWPx6SXWrQS6WkRsekMcbqi5vMuZG13TBe6KAArTa48J+C1ofAyZYUB4rbShsN6kCOlXOm86UYWa0B9VcT267zdhHSmTj3OWv4EATUo3e6IdG2JRsvrQ49vtmZAX1SvwRg3iv4huGlleiozH3jpPOIiGHzdLdXRE92BBY3EZvENOi8KNW3fxQuGA5OMhg==,iv:Opmpp023+V5WH929ie3zMrUDn+ySpsrox4SjKWFHGKM=,tag:/GIzapXm/BgzO2Nw9G4zdw==,type:str]
sops:
    lastmodified: "2026-08-08T09:58:56Z"
    mac: ENC[AES256_GCM,data:S9tfdqbR253Nd/Ns8L4wVr7bGMOOFxHeziC0P1YtBDldUIRj2ha3h892npCADcsbSKvvTQeAD9ozX+KNT52P5Lv62NpozovoD7K16j5GLwTunJkp1DnHn0cXKQKVOMLwDfsFDWyYrh+Bt7ABO21acyAMIuR1jkgeuhta1RqXBDU=,iv:uW+/3uEJk+pfPS2IivlJqXsTFlWJvpT1Lbf1Hnap5VI=,tag:D5Nea/cumbW+MaygeXhdzg==,type:str]
    pgp:
        - created_at: "2026-07-27T14:04:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4HEqjsrLGq9AQ//YcGNvS9IV+KoQ4N1ndgURn3LOSOT8Q43GZMqPd0YgiSC
            joiSmlMKn5XhfEflADU20XIknOy/PE2UM1W0O65UolNsFDN1JITseZUpy220ASJb
            na7P/SH2/wpz7YwAfW4nU0Pa6fA/5BQCuMpFdEmXBEjExwmlCD5X17YcTOCQwAqz
            AMrdmeXrG9JcV7f+llphCEECZwLE6hxN+F/JkgH+2e9XzcBlhqm2D3Z+fQbKtTOF
            tpgJ54ZBn2ot0uZ9HQ82ZcSsHA5lxx8c8DEaKpHNX4IrW83R/UOCrjQHTrLxq1bX
            nebMWPAx1c6DCk5kQFV3MPtqM5M7DnKM4K4Y8oh9kTosnZ0sJy3NRr/zQ9LliA4f
            DLy7GDX/WQ5XXpz5gnJfW2BQ9vB1Y1uVKTvwYOrkD9w9OC4qvL0PPZQRdd36vH0O
            h5sNocRvw27rME76jwCE1ARRdq9oPc/UiqIax8Fo9ylpIG5SoFdp39PW3LRfHgPN
            fLrgerfV0AL2EbzwgCt0V1iYfpfD0ky+sl7IVrZwxKBgRjo4qEYncjsEJzNtgBcj
            R0fTGk3VlJGQpDFv9w/J5eoT5Bv154IHVLSOv5iRfcwN+2/h55K1DLtEOx90XrSU
            a7+PDwk0Q1dwy+DQ1B5nd395XwCtS+eQCWwNdcMcuEHk9IZXtPScUkMwtt+1mPfS
            XAEpQGU0vGm6yy+yq2amdtCwlMgixLlMq/xRPFleuDSzZf/kmB0t4RsWcSoCkK4s
            Og3bcutrV1jjDLgSrNLJiqAgvvy15Zcurbi3tr1aVLhIsxCBr2+HhR+Rvda7
            =u6+Y
            -----END PGP MESSAGE-----
          fp: 100E6328B87F82112F2A932F7B5D8E73CC72848C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
