#ENC[AES256_GCM,data:QstgbE+FNz7dQhy6DqDjLVNwBQ+fKqEPhVDyNFhi1PuJe+OxA5H2mH+zgG45NJ1tUYk0zM3D9nfmkJ8uc3t0yFNmRvqbcAxe7Toe+WHWOBoz+ZM4sr6QThaLLqltyGAeLApVZUdcKRFPYBwk6iKwUh4kOUeJWg+mQB00jd3DVQ==,iv:ntqy0vTymIqFI04w34wU2rbQiAJ2TgDyXfT5U/t8/wE=,tag:5SWkHoK925Zeaz80lRklQQ==,type:comment]
#ENC[AES256_GCM,data:tUd3tshZko2TzHnlVmh4BmfDEfwBb9Fclqve6gDrFcOlYcbUO5CyuoQzt49eK81obcGf6d1cjWbYIKJQcyHUSFkKvLMTg/0hwbmkxuSN/pR4r/nL4Fh0,iv:fbwEEcfZr/JOh1DKjLKh3z0HtIvdFJ8Af5/p8gx+0Z8=,tag:sdef8vHVVQy08izt7cnRcg==,type:comment]
#ENC[AES256_GCM,data:J0iK9p1W8Odb5LAsET8=,iv:2TEU4gPXlnr3YF/QBVXRe7wWqlEfSsYr74X/tp1FklA=,tag:fXPAdiOtgAB1mj56MvRO/Q==,type:comment]
apiVersion: ENC[AES256_GCM,data:djW56zhzdbvVCFvi87r+F1/AwERrIg==,iv:g+WP6O0nzuYTePp6snnfbwewY8ve4RVTgsrEG/943fQ=,tag:CGhixRiP6pq8yQBKMDfG8g==,type:str]
kind: ENC[AES256_GCM,data:mBgVfBSRc/lM9x6+sFVOL8zg,iv:GynCxMdUUgWVLrZq7MkGPcBl98iEsYq/cdi5mFZmilo=,tag:gsq8lQ37QWIBfMHVwZ/a8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GXWHwYOijyFL,iv:e3RwwKv06jdeRbCovd7VHHTUu5zK133uivkqdMfXCWI=,tag:5N2L40F13ANonFhc/7uIxw==,type:str]
spec:
    #ENC[AES256_GCM,data:ACEJN9gi2ZmLhBB7ML7jyP87drTdVi7bTNting78UygSZBbdN6mPSvDqu3eDiIwCSz06Yd7NalxF/gWhSOfd/PH/3xBjRZ94DtFAT+sXLnk7uA31e/IIBaSov0s=,iv:oz6gycnuZUQfPNFyBlLuKi0z53kkrrn71YiLtdrs8UU=,tag:WNB2YBtCDFWE5RsfPp+VQg==,type:comment]
    #ENC[AES256_GCM,data:EI+JNbyuh8oevD2XMALrvxxRfA2hdJBDgixm3oDnMf7S/3YFdTv0/tFRNTWlrUGYx3e2DvqoirtR/dGKYPHSCMT0lI24t6/4gJclU5so7dlfbxhA454oJ8i9gOo=,iv:110ygrbYRdhS4hEotVNdXs84ODtL1S+XYttxUm4hSUI=,tag:UM2vR4/E3FgoQJEEPCycZw==,type:comment]
    #ENC[AES256_GCM,data:zvgzPC8o53Zki2u7vPSx2RpkddhE9TeLKf3KPTT5DoaqfMqReIi4UcYE/Lvi6ruFwtOnMblmjxV2n7fSD9Yu4MjTfcEyeQ==,iv:nZRWntNi8Xl25DOIKiN4nyqeda+h78igGv4tXq2juIU=,tag:ENINEqxrqMPmLPv7+dnoaA==,type:comment]
    conditions: []
    provider:
        bitwardensecretsmanager:
            apiURL: ENC[AES256_GCM,data:OhHAuAH3GOhtjurmDfh1msNxmSlKARQQ,iv:/mZ8YBPzyxm0F6vujdvXDTZQqIVo0ibGjccjT8sQ1fs=,tag:BT2rpG5f5ogku04OYQ4V7g==,type:str]
            identityURL: ENC[AES256_GCM,data:K9NuCPPx34oS4uGE1dJyJ+02MNtAQsQmnWKiDdA=,iv:+B6jo+K5br1ZJj49CXwKH/1dGENZmkPmA/TzDIVm5cw=,tag:7+rkkCMzvcSUVl/KzHWYnQ==,type:str]
            bitwardenServerSDKURL: ENC[AES256_GCM,data:8lpkFFrdySy/de25SY5yaEzTmF9Py+YAmA5+aNUnWVeleia3dOyoz5Tb8DI7a//hXE43OKLv/S2yuYNSGxcy56xDEj8=,iv:A/MW7KFsaYxf3Jc4a/FjPZFandQOHlXOFo8hwRJnzYc=,tag:TD8h6XDKzgkz/y2Ko21JiQ==,type:str]
            #ENC[AES256_GCM,data:82YAS/nFADDz1InXry7JHkFSPMAUXNfr0eBQuvUX/+YXhH7Wr5dnN+zcqplwuGJ396lE2h7Ms7djTMqjSpkqV51/e19lQpdPYqZd6O8BPvFDQFZJGd9Y,iv:ueCrH1vcQbxWDVy5LL+DpNMmTeQHds7JaSBSpDcBBg0=,tag:58oh8u4R9ouL4BPu34vJzw==,type:comment]
            #ENC[AES256_GCM,data:PQq/X+m1z5+t4A4gluELBiVt2w==,iv:ukm8qJJJydxdByNEZ00GeF60yeX0KIA1CbclLzGLUd8=,tag:+N3kFeGBQnC2ja+w6utk2g==,type:comment]
            caProvider:
                type: ENC[AES256_GCM,data:fCtHx6Ak,iv:15rWo4ZdPATP2qh5xQ1lpn0BFDzVbAItPjbhtjJbogE=,tag:JcDMQtsXbv0oOIi2xGfAgw==,type:str]
                name: ENC[AES256_GCM,data:qkxEiXpCJ9aA+dYhiIdcJ1h4Pg==,iv:Ee2saF1grO62suMtr4cFsBbnqkMvSms9Ej+RZLIPxyw=,tag:jgvfBj8f8AoixO51tI5tug==,type:str]
                namespace: ENC[AES256_GCM,data:p1OvWa3Cnak9fQ0Af9qi1Q==,iv:4ndypVSwfz3Sx9kPGCDCIkBpc50QHnGVHW7RjSJpuI0=,tag:kNjV8OuASVUS5fPsrB0CoQ==,type:str]
                key: ENC[AES256_GCM,data:+rXXEsyW,iv:LXQhPT64IXZdprIfVLD+C0UDgi4FeJDAqYu8B3wEfJo=,tag:incHXne8X2KEs51HVrhtFA==,type:str]
            organizationID: ENC[AES256_GCM,data:5HLeUPpH09oqPqa7NfDvEhYQ2ziNLK6JGgJT7N6Qj44yReIR,iv:gnxhhY2LnrUTzdGS1YaFqEpX4iP9QdRNKr0RXoYQTbk=,tag:GaKQXI8EWb44lRQGqelciA==,type:str]
            projectID: ENC[AES256_GCM,data:jqxJgJQ1jiD8gCrEUW08k/q5+E8xuJJs2Aob4924Ur2tnzrN,iv:+5MTWzrdArB4ShiXe3CmyQTBUtRF/p0igeHco15ZiS0=,tag:35CurOOzT7Uhe+XJmWcOKw==,type:str]
            auth:
                secretRef:
                    credentials:
                        name: ENC[AES256_GCM,data:pftZ8cE8hZpFg4VjePA2de4uPIhjww==,iv:/iBJ/fmPQyNgqP3XXDqJNUByecFlRw7BSk3AH1J5VEo=,tag:TUC71u0MYxALr69ipE/I5w==,type:str]
                        namespace: ENC[AES256_GCM,data:YQME/yb6Gpgc5RZAA5bW8A==,iv:rSh2TxW0ARJxLNssT+Ee/78ZGLr30v3tj3cA1OJuQvg=,tag:ydAySX29xN4pXL/CExqogw==,type:str]
                        key: ENC[AES256_GCM,data:bmQre8I=,iv:eVDDeQG7oCNyeRWtfWUZ7QbuAnHCMFs2FIMCVJ1z/0s=,tag:1a5/Vrht0ssxLC5RGIHEzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTEhMOUpGdTNQVWRDODFl
            dWwwd1gvSi84eHF6SWw0NVFCSUQrUnhrdVIwCmRYRVl0WVA5akErQWhqZUJHOVQy
            bTBsQ1hNRjRWNERFTlJMdS9vM0RtZzgKLS0tIFVXU2Nobk94Q29TdXBFc2dtRjFC
            RmkxRzBhcXRLTnMyaXliWGFKWEl3YlEKHkvqkN+HUjURQWhURib/i4upyJk/roY3
            NWEwr69x7BBcqQVF75EK3MZkW5TdeE0fr7gyXlQvi943n7TzPYhktQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxdu4pkrvy9k7u5wcpsa75cxls7p5q0plnsw6mscymwwflezda4qh9xvsw
    lastmodified: "2026-07-27T14:07:15Z"
    mac: ENC[AES256_GCM,data:5wNYe6ZZc4ksM3fx22qiA8KW7C49/PuJ4Yng/FsrD1nqnL65555EBR8glEPjLqo4J+YDJ5GCEY598cSbOVILE7v8/etRIg/j6OS9e4WwMahVsRUIM9QJGxaxvhcX+H2tH6PCr3jADs4/NrvjzXXnr1qRpymtqLuoAYciSNwtsEw=,iv:BBfdgRz5c1+orz9lI0YCzhNk2nbdD+KicYpOxdHyBSI=,tag:cllW4LDg5TYf3chy4Cyhjg==,type:str]
    pgp:
        - created_at: "2026-07-27T14:07:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4HEqjsrLGq9AQ/6AoRSkDxbnKbRcrgfaoUojptW5FnMH8xSJ8iLVjDG5HRb
            5APgTzZ6dfaQ/uKV4NCJgDpQRnHmpKIi+4ejdwNitOWk3EZfjLz9LwSN0srmitx5
            yBfhggdSHPIf2gCera9LI4ojSsk/4fp9OsKiTMThmjENvCUyEMshYvgH6rDGTS1p
            qCLmfTG3SrDSnvvB+UrBY3YdiYPI3HXvbfa6f5AaBGbcovHiFuAGp3YwMFrAqKVo
            23wecM6pUghxBI953bhmTcF4hVTDLAWtF2HSNfCXJaFORU11yXquleG+LX1XFEH8
            u8R/3fYfF0Iw72jf0RyRyxJfrYRbz4H9WK1ItAto4wR6QnxbgKGQMSbsf3KEHAaj
            5F1/oZ+ZKLrdqwGaNyjAJJUgWDrhrLoSOZLuFeRofJsj1UPvHEs0mfNspfiXFOLh
            mxdnhKgoQIREWwcL533nTulQPs/2I8EtHvSoM9kb2JuvZ26sDhyP8kdv4LoSYQvj
            w7KYZV1t3k9Im0yPnuCwNcoL9YMlN8ZnvFWujd60rnbQQY61svdjM6MxxuHGL+FJ
            fjuXgbpO2tUbC5pnwQlV4a3bXVsZT+I6cptsxQLKihA2o93rPZ06UgdZhy6rmCVK
            BbO1FDXH03/SKdZorzIcpMJdHqBZcdxU7tDbz9L6AjeC6LnMaHPGFwhb77Rlx1/S
            XgFuQvRIkRONwcU8QtzYL6Oh1nWcKcTVpOfk4xTyOtRqLKgZEg/fUreKjARNp1bz
            HWUechMo2MQ+hlEC33x5QTvKL+CsxrREb/ZTh1mZOIG5zym2Yjvv+6k5+Fl48Po=
            =X9Ld
            -----END PGP MESSAGE-----
          fp: 100E6328B87F82112F2A932F7B5D8E73CC72848C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
