---
# yaml-language-server: $schema=https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bao-infra
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      namespace: infra
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
