---
node:
  hostname: ogma
  os: fedora
  workflow: podman
  mesh: true
  apps: [openbao]
  ip: "{{ lookup('protonpass', 'pass://futharkd/ogma/public-ip') }}"
  initial_user: fedora
  initial_port: 22
