node_ip: ENC[AES256_GCM,data:+deZpHufxHfww9zZ,iv:fPxKdEuKEOxb/h0Mm6kki1FXMdKngG3w2uF7Nl6nzgM=,tag:DS4O8dgBiLTvrzrgx/bGLw==,type:str]
node_mesh_ip: ENC[AES256_GCM,data:cU8stKIYNb8NfQ6+,iv:doL56ESJYPZrq1iAvGLmfZSYfnIOpmR6VSME0Uh0Gks=,tag:+gDt8ptoQ+cMGletMpbccw==,type:str]
sops:
    lastmodified: "2026-07-27T16:29:01Z"
    mac: ENC[AES256_GCM,data:cMZhfnXq/eh3cM3jutLVe6qwKlmaH3Hxjq7mgBJ6cO8LQ43H2memXJzp46FPzn1+MgnsXk+JkQqxG/1aGP4LjxwjFmdhPcVjSPoQ7SWAKdbncc9WuZLNaQgWMWyOBZS2vEzitF9Y/FfRB9VcYQD1/eZUCc/cvCQqxtW2q8t51IQ=,iv:Wqty1O8n65/fPlLZPTM3AbdTUqtVuTaCGdhnSTGRThs=,tag:OYLGxEnlhePcdmyf8fEByw==,type:str]
    pgp:
        - created_at: "2026-07-27T14:02:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4HEqjsrLGq9AQ//U904VX/eDMVKk7NkCsXDaiwezpTsddxlEYiXWrxl/v6c
            DiCZlPrPh/wc3yRkZqxrNiW3EsNmMJ8KH0+oMrXNmENTgAY43iuajC1zhwt6Ax1p
            Kjh9V1XDOGlPyna0utbVIuNuMICNoUjAozI43qX+zBgznpZydNV3fyhtDNczqnVo
            Q+rIS1oV9Z7JB48FV/hrG3lgU7c7RJcrCtK4oOcUj48Nw5LbYdRhKsIjiuCU6UW2
            E5gTYFeNnX1ulEHp8ybuTQWGJU6HeTujQ1jLUzhlTbGYGe3zDLUeHLKhkDXoS0zL
            aM85ma9hX8zRMoSSPF+UvTKHaEAlqAAFU+CfpjUtZgWW8VZbhSB1yDddskkglYeY
            v3MA9FOv96ATgExbxPseEZZM82LQKVJ4xX76IgsRtQh4sR3ruO95RgipAijSn51M
            tQsLOMzfOHwc/vBgcs+Mhj8UW3xRYXipetKKfnFnDlvnQ6vfIV8OgvSkYhX7Ao9m
            6fnDfr+8x7V/3ZTrGkCxTCLt0SlmrJAY50cMkwL1YFUKR2oFvLTJmZqvapuZ7mVH
            xW5vrLdbn20CC0XZzlQfcEcLx1YrvusbGSOLTyuli7jozkIWE3rtB/8Wkt9Qcjer
            8POrwAp9Xbw+hu1rSg96yhLCARxjMM9mJhzASu3MmLrHrmEbVw+zCrI94ZBDNVbS
            XgG9Y70z8BqZ55QFijopsuVmhm7cIW9R4uIAwEz7Fx/m2koASnNkSyGrgHDX8N0I
            gtdS2k3JVsgI4lfChJFo6UZrTT9CEC3ioCU8HR73nhiEDiROtyk6QJZ/scwupxU=
            =HEBo
            -----END PGP MESSAGE-----
          fp: 100E6328B87F82112F2A932F7B5D8E73CC72848C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
