apiVersion: ENC[AES256_GCM,data:be8=,iv:vEccNrp5SKoR0BYzOKXIVcpXTojQbzfL1jahyGlz42Y=,tag:3jWDh+CDts66fe4FUAVmQQ==,type:str]
kind: ENC[AES256_GCM,data:yhHpN+mv,iv:Fgzo/mGcWcJTZiNrPIXoXLrl639ZK8oElYwjpdKQm44=,tag:ZcdjvHHJNpzrmYiHtSrLNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C1vc2YNjnfQ=,iv:UWSE53DXhfCvGWPIT/NUpiwm+UtviQckfohsFLX4sRg=,tag:ne4w6VKhg6qvSXHptqSVyA==,type:str]
    namespace: ENC[AES256_GCM,data:LrHOCKRupK4UGG4=,iv:cBGtHAJelINB+VbUReqwrZdydZKcKaUEvDrmuRdJkZM=,tag:nV2jKoOsCXFRVMCo0GlwIA==,type:str]
type: ENC[AES256_GCM,data:E7YU043L,iv:Kh4VinIwIhUU/PqIHGmtqh7Taji68KKOTTNasz3x7YI=,tag:F4+R7oo+85q9rewMwkseaw==,type:str]
stringData:
    PUBLIC_IP: ENC[AES256_GCM,data:z2QVCdbbZ9TSUSc0sA==,iv:tK2gzmrUZzdNr8X8cup/T7FXAa/bGbHPqMWifelZpfg=,tag:tJCan6M2k8iWqjCqLrJwng==,type:str]
    MESH_IP: ENC[AES256_GCM,data:06gm1zbLwFH7SEW9,iv:nfbqQ1POgo5KqU0r+bKtuaIsRkAfJJ/M/uxH+R6SkcI=,tag:a2aqYVoLLRpcbIcXOYRDzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcnMrUHJPQmZoOE1oWnlI
            enM3cTFSRGQvZ24zeFdBQmtaZ2k5SmVFUzJNClFSOXpwK1JFWVc5QjlhenZQRStI
            S2JrS1JTQmgxSjYxcU9NQ3Vva0RrV3cKLS0tIGdZMFRJTzRHZmt6Q0ZOKzYyNTBG
            UkMzbXBJdnRqR1FDT1Uzc2tBVDR6dDgK9wnnzac1/CtTlJBCbvHWRJVwfqpvE/yl
            cKF+wuUjjAo5B/I4XXJ8O1uyzHjuzpjmrL6JVmZvByqGfjJHMRHogA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxdu4pkrvy9k7u5wcpsa75cxls7p5q0plnsw6mscymwwflezda4qh9xvsw
    lastmodified: "2026-07-27T19:58:09Z"
    mac: ENC[AES256_GCM,data:w2aluqHL/i6O4QZ66TVCnTKfZYh7usVfIWxUsGjTNSBKr+gvz9KJ+nW+Mz8M6O9Uw4OTlLmF5Lgb7yhmw8uUEAPomwiMcn+I7jUzkj84jtCY/gBw/SWn2TKSBJdupNEV6+orzFn7CPQDS93sKXqTLiT7EduYpliBAedypi+HSWg=,iv:6gXRT849dIz5nxKSIBvbB1Q41sxeZvyg1pJ/dbqpEU4=,tag:Qrtp6d0I/CmC3rzoJ8ubaQ==,type:str]
    pgp:
        - created_at: "2026-07-27T14:05:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4HEqjsrLGq9ARAAlY22wsWrPG5/qVLRH0vJkxmHxt3gPRtCyv552VQH12Wc
            u3fUOUcDOY1IjnNwG3Khcbi/sPDyqpBRHx9oRRNgaWFGDRawgnNpTvNKr9rRbEgl
            m+xtU1LhrVUi4WoGjNQhwxPPc+wtlXmFlLWy1R9+ZQ9eyMAdPj37WonLxBUYp9NW
            9kR4wzFeroYKct9e1ZWucgfWXFOz8QEW770qhBZdX9uoAMwMbTKi6Dik+i+r6gqn
            5RZ+VEWk93z3EvzPcEkkES48WhxhhJW2mBUP+VnKZyhTkZtE5Un88ULv//BDOaFk
            DyVuGKfbtE8AIHCgE2bMPbBwBIYdC5DHpyjMZMdclBpdOAnh/2HrMsKdq8hLs8Z4
            S4Sfk8nLglOZtqx17IGWj3Tt/TA5PQtcxZdIgTsBmXs8Bnmc/FrtKvRVYhcoAG1O
            vGeNvv7vm7Aomrk9JKvt3lGJE0rqaqiGOUJtALRmKG/919sCNZ4f51ScSAgWrTCT
            RaaTAg3ZTKwnaMMcHcffLmodzOJU6+VYnx5l6yRf4aor1PND2k/u76+OdZc49dna
            EYlbwj1t3ba6W3XNXPRBH3wMKHrE1OjCTGrU3h6qoHO27Ah9oH9dgzcBodixPpSN
            u/MIcFaOxUSXZtZ18r9NKI29NQskNKSigA125DdIKr/OZUKjA273DfWjQ7qrH7DS
            XgE8k8Rrx8g2AyNzXF79y5Kk53ddQ6BlRiSTyfAv5FUJy6jn6h9MgTz8O5soavIN
            FrFy/9PlfEqbamIvBd6toKjg9pjOToiOoeqp9gZrLLDr1n1m7/MtoFb6Qn2KUbM=
            =KDMY
            -----END PGP MESSAGE-----
          fp: 100E6328B87F82112F2A932F7B5D8E73CC72848C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
